/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pzeDDQdgHBW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <div className="dark min-h-screen flex items-center justify-center bg-gray-900">
      <div className="w-full max-w-md bg-gray-800 rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-semibold text-white text-center">Login</h2>
        <p className="mt-2 text-center text-gray-400">Access your account</p>
        <form className="mt-4">
          <div className="flex flex-col mb-4">
            <Label htmlFor="login" className="text-gray-300">
              Login
            </Label>
            <Input
              id="login"
              type="text"
              className="px-3 py-2 bg-gray-700 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-400"
              placeholder="Enter your login"
              required
            />
          </div>
          <div className="flex flex-col mb-6">
            <Label htmlFor="password" className="text-gray-300">
              Password
            </Label>
            <Input
              id="password"
              type="password"
              className="px-3 py-2 bg-gray-700 text-white rounded-md focus:outline-none focus:ring-2 focus:ring-indigo-400"
              placeholder="Enter your password"
              required
            />
          </div>
          <Button type="submit" className="w-full py-2 px-4 bg-indigo-500 text-white rounded-md hover:bg-indigo-600">
            Sign in
          </Button>
        </form>
      </div>
    </div>
  )
}
